version: '3.8'

services:
  web:
    image: ghcr.io/haninqq/hyureservation:latest
    container_name: hyu-reservation
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --proxy-headers --forwarded-allow-ips=*
    environment:
      # Override the default SQLite database location to be within the mounted /app/data volume
      - DATABASE_URL=sqlite+aiosqlite:////app/data/rsv.db

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # If repository is private, Watchtower needs local docker credentials to pull from GHCR
      - ~/.docker/config.json:/config.json:ro
    command: --interval 300 --cleanup hyu-reservation
